apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Release.Name }}-app
  ports:
  {{- with .Values.service }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      {{- if eq .type "NodePort" }}
      nodePort: {{ .nodePort | default 30000 }}
      {{- end }}
  {{- end }}