replicaCount: 1
image:
  repository: rmanimaran/helmapp
  tag: v3
container:
  port: 8080

service:
  port: 80
  nodePort: 30000
  type: NodePort

environment: development
database:
  enabled: true
  url: "postgres://user:password@hostname:5432/dbname"

logging:
  level: "Debug"