apiVersion: v1
kind: Secret
metadata:
  name: blazor-secrets
  namespace: blazor
type: Opaque
data:
  # Base64 encoded values
  DB_CONNECTION:  U2VydmVyPWxvY2FsaG9zdDtEYXRhYmFzZT1CbGF6b3JEQjtVc2VyPXNhO1Bhc3N3b3JkPVlvdXJQYXNzd29yZDEyMyE=
  API_KEY: YWJjZGVmZ2hpams=
  JWT_SECRET: c3VwZXJzZWNyZXRrZXlmb3Jqd3R0b2tlbnM=
stringData:
  # Plain text values k8s will encode automatically
  SMTP_PASSWORD: "your-email-password"
  EXTERNAL_API_TOKEN: "Your-api-token-here"
