apiVersion: apps/v1
kind: Deployment
metadata:
  name: targetapp-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: targetapp
  template:
    metadata:
      labels:
        app: targetapp
    spec:
      containers:
      - name: targetapp-container
        image: nginx