apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "chart.name" . }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
type: Opaque
stringData:
    ConnectionStrings__DefaultConnection: {{ .Values.database.connectionString | quote }}

