apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-app
  namespace: keda-http-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-app
  template:
    metadata:
      labels:
        app: http-app
    spec:
      containers:
      - name: http-app
        image: rmanimaran/fastapi-monitoring:v4
        ports:
        - containerPort: 7755
