apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-app-scaledobject
  namespace: keda-http-app
spec:
  scaleTargetRef:
    name: http-app
    kind: Deployment
    apiVersion: apps/v1
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 15
  cooldownPeriod: 30
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.keda-http-app.svc.cluster.local:80
      query: sum(irate(http_request_total[2m]))
      threshold: '10'