apiVersion: v1
kind: Service
metadata:
  name: http-app-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: http-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 7755
  type: LoadBalancer